### ISSUE TITLE
BUG:  Registered users cannot see the members of public ecoverses

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1358]
**Describe the bug**
As a registered user I would like to see what members there are in an organisation / community; or to get a message that I cannot see the members

**To Reproduce**
Login as a non-admin user
Go to digicampus ecoverse page
No members are visible

**Expected behavior**
Registered users should be able to see the members of a non-private organisation / community
Registered users should not be able to see the members of a private community (ecoverse / challenge etc)

**Comment by Comoque1** [comment]
Tested on DEV env after performing reset Organisation/Ecoverse credential mutations.
Regarding first point of expected behavior - looks OK:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3a51c33a-fa2d-407d-949e-c7558cd91e55)

Regarding second point of expected behavior, raised [new bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1374)
