### ISSUE TITLE
Update challenges on ecoverse to not use eager loading

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#143]
## Description
As a populator of an ecoverse I want that the process is fast, or at least remains relatively stable as the number of users / groups increases. 

It is noticeable that as the number of users increases when doing the data loading that the response time from the server also increases. Worst place seems to be in the addUserToGroup mutation, and then within that mutation it seems that it takes a growing amount of time to find the right UserGroup.

## Acceptance criteria

- [ ] Migrate challenges on the ecoverse to not be eager loaded

**Comment by atstoyanov** [comment]
Adding more data makes loading the Ecoverse slower and slower. Here are visible loading times. After each time user is added, the loading time increase with around 300ms.

![EcoverseLoadingTimings.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/4ad9b80f-b936-4761-a6e7-80009d0727eb)

With just 22 users in the database the loading time is nearly 5s.
The Ecoverse is used for validation existance of each, related entity, because of that is loaded before each mutation.
The loading times are because of the eager loading. Better solution will be to load only required entities.

**Comment by techsmyth** [comment]
Makes sense - and this is also what I saw in my data loading loops.

Challenge is where to put in lazy loading - need a discussion?
