### ISSUE TITLE
memberof query has empty groups

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#311]
**Describe the bug**
the memberof query has empty groups i.e. the right groups are there but they do not have any members

**To Reproduce**
1. Populate an ecoverse with some sample data
2. run a query that returns a single user, and then on that user have the following sub-query:
memberof {
    groups {
        name
        members {
           name
       }
   }
}
The members group is empty which should not be the case

**Comment by Comoque1** [comment]
Merging [this issue](https://app.zenhub.com/workspaces/cherrytwist-5ecb98b262ebd9f4aec4194c/issues/cherrytwist/server/332) to the current one, as they overlap:

Steps to reproduce the behavior:
1. Go to [env](http://localhost:4000/graphql)
2. Create a Challenge
3. Create a Group and link it to the Challenge
4. Create a User and add it to the Challenge and to the Group
5. Use the following queries to find the User in the Challenge and in the Group

```
query{
  group (ID: 122){
    name,
    id,
    profile{
      references{
        name
      }
    }
    members{
      name,
      id
      memberof {
        challenges {
          name
          id
        }}}}}
```

```
query {
  challenge (ID: 17){
    name,
    contributors{
      name
      id
    }
    groups {
      name
      id
      members
      {
        name
        id
      }}}}
```

**Expected behavior**
The Users added to the Group, must be available in the results, under groups `{ members{ name id } }`

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cffb9317-9d68-4d92-8674-0b42dba55b68)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a74c4084-a2a4-403d-aa68-275fbecfcdb4)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/45a1b8f5-81c4-42e1-8d57-e5d1a4a9973f)

**Comment by Comoque1** [comment]
**Tested OK on Dev environment**

```
query {
  users {
    name
    id
    email
    memberof {
      groups {
        name
        members {
          name
        }
      }
      challenges {
        name
        contributors {
          name
        }
      }
    }
  }
}
```

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ae2f592e-db99-4f78-8018-1fd740ffd59c)
