### ISSUE TITLE
Extend connection factory to use ormconfig + migration support is enabled

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#53]
## Description
As a developer I want a connection factory so that migrations can take place and it is also simply better that the parameters are specified in a config file(i.e. entries that are not environment specific)

## Acceptance criteria

- [ ] add typeorm static and default configuration to .env.default and .env.docker
- [ ] Update readme to detail out using .env.default for local development
- [ ] migrations are enabled between versions of the database schema e.g. update the db schema

**Comment by jellelicht** [comment]
There seems to be a bug in typeorm (and has been for at least 1 year) that prevents us from taking the 'fun' route of using environment variables to configure all the boring bits via `ormconfig.env` and normal environment variables for actual configuration and/or secrets. 

I can work around this in 2 distinct ways:
1. Instead of `ormconfig.env`, use `.env` for all typeorm-related static settings. Get the rest (automagically) from the environment.
2. Go with ormconfig.js: we will have to extract what we need from the environment and recombine it correctly. This works, but must be kept in sync with `connection-factory.ts`.

The original option (of `ormconfig.json`) wouldn't work without some serious elbow grease; typeorm _actively ignores_ all environment variables if it detects an ormconfig.json file; since we only want to store static, non-secret information in the json. An options here is to duplicate parts of `typeorm` internals in manually merging the settings (we think) we are interested in.

Of course, we could also fork `typeorm` for now, and open a PR to support this. It seems the author has been working on a different solution for now though, with no clear timeline on when they can deliver.

@valentinyanakiev what would you prefer?

**Comment by valentinyanakiev** [comment]
> There seems to be a bug in typeorm (and has been for at least 1 year) that prevents us from taking the 'fun' route of using environment variables to configure all the boring bits via `ormconfig.env` and normal environment variables for actual configuration and/or secrets.
> 
> I can work around this in 2 distinct ways:
> 
> 1. Instead of `ormconfig.env`, use `.env` for all typeorm-related static settings. Get the rest (automagically) from the environment.
> 2. Go with ormconfig.js: we will have to extract what we need from the environment and recombine it correctly. This works, but must be kept in sync with `connection-factory.ts`.
> 
> The original option (of `ormconfig.json`) wouldn't work without some serious elbow grease; typeorm _actively ignores_ all environment variables if it detects an ormconfig.json file; since we only want to store static, non-secret information in the json. An options here is to duplicate parts of `typeorm` internals in manually merging the settings (we think) we are interested in.
> 
> Of course, we could also fork `typeorm` for now, and open a PR to support this. It seems the author has been working on a different solution for now though, with no clear timeline on when they can deliver.
> 
> @valentinyanakiev what would you prefer?

I don't really want to use ormconfig.env as that will leave us with .env, .env.default and ormconfig.env and we'll need to combine and support the README. That will confuse contributors. I'd say keep .env and .env.default. I'd say perfect option would be ormconfig.json to support environment variables in general and we should create an issue (and potentially PR) in typeorm for it. Option #2 seems like a solution, but then we'll have to be careful on typeorm updates as config file structure might change in the future. @jellelicht let's discuss privately when you have time.
