### ISSUE TITLE
references to configuration for server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#840]
## Description
As a deployer of Cherrytwist I want to be able to customise key links within the application

## Acceptance criteria

- [ ] add new references section under Config in the api that contains a list of references (name, uri, description)
- [ ] expand configuration loaded to specify three URLS; feedback, terms-of-use, privacy that will then appear under the configuration/references api

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ad2a5a50-4d91-473b-875b-86f770a8b427)

**Comment by valentinyanakiev** [comment]
I have pushed an easy quick fix, but we need to know the following in order to make a good design:

- Do we get the entities from the database through a service?
   - If not, I need to either create a new DTO for the return Reference object excluding the ID, or to 'fake' the IDs to values I know are not perent in the DB
   - If yes, we need to design this separately and get the config from the DB.

There is also the issue where I couldn't find a link to  terms-of-use - currently dev has them on https://dev.cherrytwist.org/terms-of-use.html. This should be a link to 3rd party URL. What is the URL.

There is a draft pushed, easy-to-amend at the moment, but I don't believe it's ready to be merged.

**Comment by techsmyth** [comment]
> I have pushed an easy quick fix, but we need to know the following in order to make a good design:
> 
> * Do we get the entities from the database through a service?
>   
>   * If not, I need to either create a new DTO for the return Reference object excluding the ID, or to 'fake' the IDs to values I know are not perent in the DB
>   * If yes, we need to design this separately and get the config from the DB.
> 
> There is also the issue where I couldn't find a link to terms-of-use - currently dev has them on https://dev.cherrytwist.org/terms-of-use.html. This should be a link to 3rd party URL. What is the URL.
> 
> There is a draft pushed, easy-to-amend at the moment, but I don't believe it's ready to be merged.

Lets take an hour on Monday to brainstorm the configuration path forward. 

Just had a look at the branch + a couple of first reaction comments:
- this is about having a general config mechanism, so the core setup looks good
- the contents of the three default references are specific to the deployment of CT, so whoever is hosting the ecoverse. By default they should link to locations on the main CT website. In general these references can point anywhere. Key is that they are not hard coded in the client. 
- edits for text contents below. With these updates the PR is IMHO ok to go in.

The contents of the default files does need work - will pick up with Rene next week. 

{
  "references": [
    {
      "id": -3,
      "name": "feedback",
      "description": "Default user feedback location for a Cherrytwist instance",
      "uri": "https://cherrytwist.org/ecoverse/feedback"
    },
    {
      "id": -2,
      "name": "terms-of-use",
      "description": "Default Terms of Use for a Cherrytwist instance",
      "uri": "https://cherrytwist.org/ecoverse//terms-of-use"
    },
    {
      "id": -1,
      "name": "privacy-policy",
      "description": "Default Privacy Policy for a Cherrytwist instance",
      "uri": "https://cherrytwist.org/ecoverse/privacy"
    }
  ]
}

@ReneHonig good to also involve you in this setup discussion...
